DWAPlannerROS:
  max_vel_trans: 0.5
  min_vel_trans: 0.1
  max_vel_x: 0.5
  min_vel_x: -0.5
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  acc_lim_x: 1.0
  acc_lim_theta: 2.0

  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: true

  sim_time: 1.7
  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.05

  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

  publish_traj_pc: true
  publish_cost_grid_pc: false

  meter_scoring: true